import Head from "next/head";
import NavBar from "../components/Global/NavBar";
import Banner from "../components/Home/Banner";
import Main from "../components/Home/Main";
import Footer from "../components/Global/Footer";

export default function Home({ exploreData, liveAnywhere }) {
  return (
    <div>
      <Head>
        <title>Airbnb clone by Cong Ta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Banner />
      <Main exploreData={exploreData} liveAnywhere={liveAnywhere} />
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://jsonkeeper.com/b/4G1G").then(
    (result) => result.json()
  );

  const liveAnywhere = await fetch("https://jsonkeeper.com/b/VHHT").then(
    (result) => result.json()
  );

  return {
    props: {
      exploreData: exploreData,
      liveAnywhere: liveAnywhere,
    },
  };
}
