import React from "react";
import Head from "next/head";
import NavBar from "../components/Global/NavBar";
import Footer from "../components/Global/Footer";
import Main from "../components/Search/Main";
import { useRouter } from "next/router";
import { format } from "date-fns";

function Search({searchResult}) {
  const router = useRouter();
  const { location, startDate, endDate, guess } = router.query;

  const formatStartDate = format(new Date(startDate), "dd MMMM yy");
  const formatEndDate = format(new Date(endDate), "dd MMMM yy");
  const range = `${formatStartDate} - ${formatEndDate}`;

  return (
    <main>
      <Head placeholder={`${location} | ${range} | ${guess}`}>
        <title>Airbnb Search by Cong Ta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main location={location} guess={guess} range={range} searchResult={searchResult}/>
      <Footer />
    </main>
  );
}

export default Search;

export async function getServerSideProps() {
  const searchResult = await fetch("https://links.papareact.com/isz").then(
    (res) => res.json()
  );

  return {
    props: {
      searchResult: searchResult,
    },
  };
}
